<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>FauxData</PackageId>
    <Version>1.0.0</Version>
    <Authors>Dieter Van Broeck</Authors>
    <Description>Fake data generator with rule-based configuration.</Description>
    <PackageTags>fake;test-data;faker;testing</PackageTags>
    <PackageLicenseExpression>MIT-0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/you/Faux</RepositoryUrl>
    <PackageProjectUrl>https://github.com/you/Faux</PackageProjectUrl>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
